-
  name: Install Ngnix and Start it
  hosts: webservers
  become: yes
  tasks:
    - name: Install Nginx
      apt:
        name: nginx
        state: latest
    - name: Start Nginx
      service:
        name: ngnix
        state: started
        enabled: yes

    - name: Deploy Web Page
      copy:
        src: index.html
        dest: /var/www/html
